spring:
  application:
    name: cowing-msa-orderbook

  config:
    activate:
      on-profile: local

  data:
    redis:
      host: localhost
      port: 6379

---

spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 1