spring:
  application:
    name: cowing-msa-orderbook

  config:
    activate:
      on-profile: local

  data:
    redis:
      host: localhost
      port: 6379
      # local 환경에도 연결 풀 설정 추가
      lettuce:
        pool:
          max-active: 12
          max-idle: 6
          min-idle: 3
          max-wait: 5000ms
      timeout: 3000ms

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 3000ms          # 2000ms → 3000ms 증가
      lettuce:
        pool:
          max-active: 12       # 1 → 12 증가 ✨
          max-idle: 6          # 새로 추가 ✨
          min-idle: 3          # 새로 추가 ✨ 
          max-wait: 5000ms     # 새로 추가 ✨

server:
  port: ${SERVER_PORT:8081}

websocket:
  url: ${BROADCASTER_WEBSOCKET_URL}