name: CICD for orderbook

on:
  push:
    branches: [ "main" ]
 
env:
  REGISTRY: ghcr.io
  GITOPS_REPO: CoinWing/Infrastructure

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [msa-orderbook]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set lowercase image name
        id: image_name
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="${LOWERCASE_OWNER}/cowing-msa-orderbook"
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Generate version tag
        id: version
        run: |
          DATE_VERSION="$(date +'%Y.%m.%d')"
          SHORT_SHA="$(echo $GITHUB_SHA | cut -c1-7)"
          VERSION="${DATE_VERSION}-${SHORT_SHA}"
          echo "Generated version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Spring Boot Build
        run: ./gradlew clean build --exclude-task test

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.image_name.outputs.image_name }}:${{ steps.version.outputs.version }}
            ${{ env.REGISTRY }}/${{ steps.image_name.outputs.image_name }}:latest 

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops
          ref: prod

      - name: Update image tag in kustomization.yaml
        run: |
          TAG="${{ steps.version.outputs.version }}"
          IMAGE="ghcr.io/coinwing/${{ matrix.service }}"
          FILE="gitops/code/argocd/kustomize/${{ matrix.service }}/kustomization.yaml"

          sed -i "s|newTag: .*|newTag: ${TAG}|" $FILE

      - name: Commit and push changes to GitOps repo
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add code/argocd/kustomize/${{ matrix.service }}/kustomization.yaml
          git commit -m "chore(${{ matrix.service }}): bump image tag to ${TAG}"
          git push origin prod
